### ISSUE TITLE
strongly recommend to use Pytorch or Tensorflow as computing platform in the future　:)

### ISSUE THREAD

**Issue by YihangLou** [filipradenovic/cnnimageretrieval#3]
Hi filip, your code is written very elegant and with amazing performance. But I recommend you to use Pytorch or tensorflow for your future work. Since matconvnet is not friendly to quickly use and development community is not strong. Moreover the training efficiency and deployment would be inferior to  the above platforms. Python is more convenient to process network and data.

Thanks for your code sharing again !

**Comment by filipradenovic** [comment]
Hello, thank you for your recommendation. In fact, we are working on a PyTorch version of the same toolbox, that should be available soon. I hope you will like it!

**Comment by filipradenovic** [comment]
@YihangLou PyTorch version available here: https://github.com/filipradenovic/cnnimageretrieval-pytorch
