### ISSUE TITLE
CUDA support for matconvnet?

### ISSUE THREAD

**Issue by mohsij** [filipradenovic/cnnimageretrieval#4]
Is matconvnet compiled with or without cuda support? If it is with cuda support could you give more details on what driver version and toolkit version was used. Thanks!

**Comment by filipradenovic** [comment]
I would suggest you to check out these instructions: http://www.vlfeat.org/matconvnet/install/

**Comment by mohsij** [comment]
Thank you, I just wanted to know whether matconvnet was compiler with GPU support or not. After reading the papers it was clear that it was
