### ISSUE TITLE
error in get_images()

### ISSUE THREAD

**Issue by RuibinMa** [filipradenovic/cnnimageretrieval#6]
Hi,
Thanks for sharing code. I got the following error. Any suggestions?
>> Validation images not provided, loading...
>>>> imageDir: /playpen/cnnimageretrieval/data/train/ims
>>>> Running on GPU GeForce GTX TITAN X with Index 1

>>>> [  0.00%] [          ] [t ?] [e 0.0s] [r ?] Error using imresizegpumex
Expected input scale to be a real, positive scalar of numeric type on the CPU.

Error in gpuArray/imresize (line 46)
B = imresizegpumex(varargin{:});

Error in imresizemaxd (line 19)
		im = imresize(im, [sz NaN], method);

Error in get_images>@(x)imresizemaxd(x,opts.imageSize)

Error in get_images>getImageBatch (line 78)
  data = cellfun(@(x) imresizemaxd(x, opts.imageSize), data, 'UniformOutput', false);

**Comment by filipradenovic** [comment]
This looks like a MATLAB version incompatibility. Which version of MATLAB are you using? Can you try running it with MATLAB R2017a, as suggested in the README?

**Comment by RuibinMa** [comment]
No I'm using 2015b. Maybe that's the reason. I've tried the pytorch version and that works well. Thanks!
