### ISSUE TITLE
Adam solver issue

### ISSUE THREAD

**Issue by frash83** [filipradenovic/cnnimageretrieval#7]
It gives me an error for the following line:
assert(isa(opts.train.solver, 'function_handle') && nargout(opts.train.solver) == 2,...
		'Invalid solver; expected a function handle with two outputs.');

Error using nargout
Function solver.adam does not exist.

It seems there is no @solver.adam in Matlab R2017a.

**Comment by filipradenovic** [comment]
@solver.adam is from MatConvNet, not MATLAB. This is the [implementation](https://github.com/vlfeat/matconvnet/blob/master/examples/%2Bsolver/adam.m). Make sure you are using MatConvNet toolbox version [1.0-beta25](http://www.vlfeat.org/matconvnet/download/matconvnet-1.0-beta25.tar.gz), and it should work.
