### ISSUE TITLE
Oxford5k groundtruth

### ISSUE THREAD

**Issue by flyinsky323** [filipradenovic/cnnimageretrieval#8]
Hello, do you have a complete groundtruth file with the Oxford5k image set? Can you send it? I downloaded incomplete.My Email is flyinsky323@126.com

**Comment by filipradenovic** [comment]
What exactly do you mean by incomplete? The groundtruth file that gets downloaded when using this code should be complete.

The groundtruth file is available [here](http://cmp.felk.cvut.cz/cnnimageretrieval/data/test/oxford5k/gnd_oxford5k.mat).
